name: Pre Merge Checks
on:
  push:
    paths-ignore:
      - diagrams/**
      - README.md
  pull_request:
    paths-ignore:
      - diagrams/**
      - README.md

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target test --tag todo-app:test .
      - run: docker run --rm todo-app:test
