name: Pre Merge Checks
on:
  push:
    paths-ignore:
      - diagrams/**
      - README.md
  pull_request:
    paths-ignore:
      - diagrams/**
      - README.md

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: todo-app:test
          target: test
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha
      - run: docker run todo-app:test
